name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
#    - run: npm test
#      env:
#        CI: true
#    - run: npm run build
    - name: ‘Deploy to Server’
      uses: appleboy/ssh-action@master
      with:
        host: "44.216.122.164"
        username: "ubuntu"
        key: ${{ secrets.SSH_PRIVATE_KEY1 }}
        script: |
          cd /home/ubuntu/backend
          git pull